[package]
name = "natti"
version = "0.1.0"
authors = ["Coleman McFarland <coleman.mcfarland+dontlaugh@gmail.com>"]
edition = "2018"

[dependencies]
nats = "0.7.2"
pico-args = "0.3.4"
toml = "0.5.6"
anyhow = "1.0.32"

